server:
  port: 8086


spring:
  datasource:
    url: jdbc:h2:mem:tiny-url;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  cache:
    type: redis

  redis:
    host: 192.168.99.100
    port: 6379

